name: feeds
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  intl:
  http:
  after_layout: ^1.2.0
  sizer: ^2.0.15
  streaming_shared_preferences: ^2.0.0
  flutter_spinkit: ^5.2.0
  get_it: ^7.6.4
  mobx: ^2.2.0
  circular_countdown_timer: ^0.2.3
  flash:
  flutter_svg:
  flutter_mobx: ^2.1.0
  provider: ^6.0.5
  injectable: ^2.3.0
  lottie:
  flutter_animate:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.3
  build_runner: ^2.4.6
  mobx_codegen: ^2.3.0
  injectable_generator: ^2.4.0


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/lottie/